players = [
'<a href="http://www.ianbaxter.net/">Ian Baxter</a>',
'<a href="http://soundcloud.com/bycrookorbyhook">Nice</a>',
'<a href="http://www.markfell.com/">Mark Fell</a>',
'<a href="http://johnmoseley.co.uk/">John Moseley</a>',
'<a href="http://helopg.co.uk/">HELOpg</a>',
'<a href="http://yaxu.org/">yaxu</a>',
'<a href="http://www.ardisson.net/">Charles Matthews</a>',
'<a href="http://www.wix.com/stanandmatt/the-skinny-theatre-page">Stan Skinny</a>',
'<a href="http://www.spacers.lowtech.org/herve/">sndsukinspook</a>',
'Daniel Massey',
'<a href="http://stretch.deedah.org">Martyn Eggleton</a>',
'<a href="http://audiolaceration.com">Foster</a>',
'<a href="http://audiotools.lowtech.org">Jake Harries</a>',
'<a href="http://blocprojects.co.uk/studios/studio-holders/susanne-palzer/">Susanne Palzer</a>',
'<a href="http://www.sunshinegray.co.uk/">Sunshine Gray</a>',
'<a href="http://www.ronwright.org/">Ron Wright & Neil Webb & David Morin</a>',
'<a href="http://deedah.org/zomaz">Steve Withington</a>',
'<a href="http://www.sheffieldelectricity.com">Jen Rich</a>',
'<a href="http://soundcloud.com/deliberate">Deliberate</a>',
'<a href="http://dinisnoise.org">Jagernot</a>',
'<a href="http://richardbolam.wordpress.com/">Hard Shoulder</a>',
'<a href="http://soundcloud.com/parcel-shelf">Parcel Shelf</a>',
'<a href="http://www.thecuriousmachine.com/">The Curious Machine</a>',
'<a href="http://www.ravelite.org/">Graham Coleman</a>',
'<a href="http://soundcloud.com/swan-hunter">Swan-Hunter</a>',
'<a href="https://www.facebook.com/pages/Section_9/147249975348027?sk=wall">section_9</a>',
'<a href="http://cmx.org.uk/">Phil Julian</a>'
];
